website/views.py
from flask import Flask, Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from . import db
from .models import User, Comment


from packages import l471_df, l474_df, l424_df, l429_df, l458_df



app = Flask(__name__, template_folder='templates', static_folder='static')

views = Blueprint('views', __name__)


def get_last_comment():
    return Comment.query.filter_by(user_id=current_user.first_name + ' ' + current_user.last_name).order_by(Comment.id.desc()).first()


from website import TIMEZONE
from datetime import datetime

def get_new_comment_count():
    last_visit = current_user.last_visit  

    if last_visit is None:  # if the user is visiting for the first time, return total comment count
        return Comment.query.count()
    else:
        new_comments = Comment.query.filter(Comment.timestamp > last_visit).count()
        return new_comments


@views.route('/')
@login_required
def home():
    return render_template("index.html", user=current_user)

@views.route('/reset_new_comment_count', methods=['POST'])
@login_required
def reset_new_comment_count():
    current_user.last_visit = datetime.now(tz=TIMEZONE)
    db.session.commit()
    return redirect(url_for('views.profile'))

@views.route('/474', methods=['GET', 'POST'])
@login_required
def l_474():
    if request.method == 'POST':
        lineNumber = request.form.get('lineNumber')
        dayOfWeek = request.form.get('dayOfWeek')
        subject = request.form.get('subject')
        comment = request.form.get('comment')
        downTimeType = request.form.get('downtimeType')  # Get the selected downtime type
        user_id = current_user.first_name + ' ' + current_user.last_name  # add a space between first name and last name
        new_comment = Comment(lineNumber=lineNumber, dayOfWeek=dayOfWeek, subject=subject, comment=comment, user_id=user_id, downTimeType=downTimeType)
        db.session.add(new_comment)
        try:
            db.session.commit()
            flash('Comment saved successfully', category="success")
        except:
            db.session.rollback()
            flash('Failed to save comment', category="error")
    
    return l474_df()

  

@views.route('/471', methods=['GET', 'POST'])
@login_required
def l_471():   
    if request.method == 'POST':
        lineNumber = request.form.get('lineNumber')
        dayOfWeek = request.form.get('dayOfWeek')
        subject = request.form.get('subject')
        comment = request.form.get('comment')
        user_id = current_user.first_name + ' ' + current_user.last_name  # add a space between first name and last name
        new_comment = Comment(lineNumber=lineNumber, dayOfWeek=dayOfWeek, subject=subject, comment=comment, user_id=user_id)
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment saved successfully', 'success')
    return l471_df()

@views.route('/424', methods=['GET', 'POST'])
@login_required
def l_424():
    if request.method == 'POST':
        lineNumber = request.form.get('lineNumber')
        dayOfWeek = request.form.get('dayOfWeek')
        subject = request.form.get('subject')
        comment = request.form.get('comment')
        user_id = current_user.first_name + ' ' + current_user.last_name  # add a space between first name and last name
        new_comment = Comment(lineNumber=lineNumber, dayOfWeek=dayOfWeek, subject=subject, comment=comment, user_id=user_id)
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment saved successfully', 'success')
    return l424_df()

@views.route('/429', methods=['GET', 'POST'])
@login_required
def l_429():
    if request.method == 'POST':
        lineNumber = request.form.get('lineNumber')
        dayOfWeek = request.form.get('dayOfWeek')
        subject = request.form.get('subject')
        comment = request.form.get('comment')
        user_id = current_user.first_name + ' ' + current_user.last_name  # add a space between first name and last name
        new_comment = Comment(lineNumber=lineNumber, dayOfWeek=dayOfWeek, subject=subject, comment=comment, user_id=user_id)
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment saved successfully', 'success')
    return l429_df()

@views.route('/458', methods=['GET', 'POST'])
@login_required
def l_458():
    if request.method == 'POST':
        lineNumber = request.form.get('lineNumber')
        dayOfWeek = request.form.get('dayOfWeek')
        subject = request.form.get('subject')
        comment = request.form.get('comment')
        user_id = current_user.first_name + ' ' + current_user.last_name  # add a space between first name and last name
        new_comment = Comment(lineNumber=lineNumber, dayOfWeek=dayOfWeek, subject=subject, comment=comment, user_id=user_id)
        db.session.add(new_comment)
        db.session.commit()
        flash('Comment saved successfully', 'success')
    return l458_df()

@views.route('/461', methods=['GET', 'POST'])
@login_required
def menu461():
    return render_template("461.html", user= current_user)







from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from flask import current_app, url_for
from .models import User
from flask_mail import Mail

@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        if request.form.get('reset_form'):
            current_password = request.form.get('password')
            new_password = request.form.get('new_password')
            confirm_new_password = request.form.get('confirm_new_password')
            if new_password and confirm_new_password:
                if check_password_hash(current_user.password, current_password):
                    if check_password_hash(current_user.password, new_password):
                        flash('Your new password cannot be the same as your old password', 'error')
                    elif new_password != confirm_new_password:
                        flash('Passwords do not match', category='error')
                    else:
                        current_user.password = generate_password_hash(new_password)
                        db.session.commit()
                        flash('Your password has been reset', 'success')
                else:
                    flash('Current password is incorrect', 'error')
            else:
                flash('Please enter both new password and confirmation password', 'error')
        elif request.form.get('message'):
            name = request.form.get('name')
            email = request.form.get('email')
            message = request.form.get('message')
            send_mail(name, email, message)
            flash("Message sent! Thank you for contacting us.", category="success")
        else:
            flash("All fields are required.", category="error")
    last_comment = get_last_comment()
    new_comments = get_new_comment_count()
    
    return render_template('profile.html', last_comment=last_comment, user=current_user, new_comments=new_comments)


def send_mail(name, email, message):
    admins = User.query.filter_by(is_admin=True).all()
    if not admins:
        return
    mail = Mail(current_app)
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    for admin in admins:
        token = s.dumps(admin.email, salt=current_app.config['SECURITY_PASSWORD_SALT'])
        msg = Message(
            'New Contact Form Submission',
            sender=current_user.email,
            recipients=[admin.email]
        )
        msg.body = f"Hi {admin.first_name},\n\nA new message has been submitted from the contact form:\n\nName: {name}\nEmail: {email}\nMessage: {message}"
        mail.send(msg)



@views.route("/get_updated_data")
def get_updated_data():
  # Call your l429_df function to get the updated data
  updated_data = l429_df()
  # Return the updated data in JSON format
  return jsonify({"data": updated_data})

website/templates/424.html
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"defer></script>

<link rel="stylesheet" href="{{ url_for('static', filename= 'comments.css')}}">
<script src="/static/comments.js" defer></script>

<html>
{% extends 'base.html' %}
{%block title%}
Accuride
{%endblock%}
{%block content%}
<main>

        <div class="body-container">
          <table class="l474" id="data-table">
              <thead>
                <tr>
                  {% for column in data[0].keys() %}
                  <th>{{ column }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for row in data %}
                <tr>
                  {% for value in row.values() %}
                  <td>{{ value }}</td>
                  {% endfor %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

          <div class="row2">
            <div class="img-container">
            <img class="first-img-block" src="https://www.accuridecorp.com/sites/default/files/media/images/2023-03/Red%20Truck_edit%201.png">
            <div class="subhead"><h1 id="linenumb">Line 424</h1></div>
            </div>
            <div class="section-2">
              <div class="section-cube-1">
                <h1>Part Totals</h1>
                <div class="table-2-container"> 
                  <table id="weektotals-tb">
                    <thead>
                      <tr>
                        <th>Week Day</th>
                        <th>Total Parts</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekday, total_parts in weekday_parts %}
                      <tr>
                        <td>{{ weekday }}</td>
                        <td>{{ total_parts }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="table-3-img" src="static/Images/Test.png" alt="">
                    <img id="table-2-img" src="static/Images/TestWhite.png" alt="">
                    <img id="table-3-img" src="static/Images/Test.png" alt="">
               
                  </div>              
                </div>
             </div>
            </div>

            <div class="section-2">
              <div class="section-cube-1">
                <h1>Starved</h1>
                <div class="table-2-container"> 
                  <table id="starved-tb">
                    <thead>
                      <tr>
                        <th>Week Day</th>
                        <th>Starved Time(min)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekdays, Total in weekday_starved  %}
                      <tr>
                        <td>{{ weekdays }}</td>
                        <td>{{ Total }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="stable-3-img" src="static/Images/starved.png" alt="">
                  </div>              
                </div>
              </div>
            </div>

            <div class="section-2">
              <div class="section-cube-1">
                <h1>Blocked</h1>
                <div class="table-2-container"> 
                  <table id=".blocked-tb">
                    <thead>
                      <tr>
                        <th>Weekday</th>
                        <th>Blocked Time(min)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekdayd, Total in weekday_blocked  %}
                      <tr>
                        <td>{{ weekdayd }}</td>
                        <td>{{ Total }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="btable-3-img" src="static/Images/Blocked.png" alt="">
                    
                  </div>              
                </div>
             </div>
            </div>
            
          </div> 

      </main>  
{%endblock%}   

</html>

website/templates/429.html
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"defer></script>

<link rel="stylesheet" href="{{ url_for('static', filename= 'comments.css')}}">
<script src="/static/comments.js" defer></script>

<html>
{% extends 'base.html' %}
{%block title%}
Accuride
{%endblock%}
{%block content%}
<main>

        <div class="body-container">
          <table class="l474" id="data-table">
              <thead>
                <tr>
                  {% for column in data[0].keys() %}
                  <th>{{ column }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for row in data %}
                <tr>
                  {% for value in row.values() %}
                  <td>{{ value }}</td>
                  {% endfor %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

          <div class="row2">
            <div class="img-container">
            <img class="first-img-block" src="https://www.accuridecorp.com/sites/default/files/media/images/2023-03/Red%20Truck_edit%201.png">
            <div class="subhead"><h1 id="linenumb">Line 429</h1></div>
            </div>
            <div class="section-2">
              <div class="section-cube-1">
                <h1>Part Totals</h1>
                <div class="table-2-container"> 
                  <table id="weektotals-tb">
                    <thead>
                      <tr>
                        <th>Week Day</th>
                        <th>Total Parts</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekday, total_parts in weekday_parts %}
                      <tr>
                        <td>{{ weekday }}</td>
                        <td>{{ total_parts }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="table-3-img" src="static/Images/Test.png" alt="">
                    <img id="table-2-img" src="static/Images/TestWhite.png" alt="">
                    <img id="table-3-img" src="static/Images/Test.png" alt="">
               
                  </div>              
                </div>
             </div>
            </div>

            <div class="section-2">
              <div class="section-cube-1">
                <h1>Starved</h1>
                <div class="table-2-container"> 
                  <table id="starved-tb">
                    <thead>
                      <tr>
                        <th>Week Day</th>
                        <th>Starved Time(min)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekdays, Total in weekday_starved  %}
                      <tr>
                        <td>{{ weekdays }}</td>
                        <td>{{ Total }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="stable-3-img" src="static/Images/starved.png" alt="">
                  </div>              
                </div>
              </div>
            </div>

            <div class="section-2">
              <div class="section-cube-1">
                <h1>Blocked</h1>
                <div class="table-2-container"> 
                  <table id=".blocked-tb">
                    <thead>
                      <tr>
                        <th>Weekday</th>
                        <th>Blocked Time(min)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekdayd, Total in weekday_blocked  %}
                      <tr>
                        <td>{{ weekdayd }}</td>
                        <td>{{ Total }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="btable-3-img" src="static/Images/Blocked.png" alt="">
                    
                  </div>              
                </div>
             </div>
            </div>
            
          </div> 

      </main>  
{%endblock%}   

</html>

website/templates/458.html
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js"defer></script>

<link rel="stylesheet" href="{{ url_for('static', filename= 'comments.css')}}">
<script src="/static/comments.js" defer></script>

<html>
{% extends 'base.html' %}
{%block title%}
Accuride
{%endblock%}
{%block content%}
<main>

        <div class="body-container">
          <table class="l474" id="data-table">
              <thead>
                <tr>
                  {% for column in data[0].keys() %}
                  <th>{{ column }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for row in data %}
                <tr>
                  {% for value in row.values() %}
                  <td>{{ value }}</td>
                  {% endfor %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>

          <div class="row2">
            <div class="img-container">
            <img class="first-img-block" src="https://www.accuridecorp.com/sites/default/files/media/images/2023-03/Red%20Truck_edit%201.png">
            <div class="subhead"><h1 id="linenumb">Line 458</h1></div>
            </div>
            <div class="section-2">
              <div class="section-cube-1">
                <h1>Part Totals</h1>
                <div class="table-2-container"> 
                  <table id="weektotals-tb">
                    <thead>
                      <tr>
                        <th>Week Day</th>
                        <th>Total Parts</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekday, total_parts in weekday_parts %}
                      <tr>
                        <td>{{ weekday }}</td>
                        <td>{{ total_parts }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="table-3-img" src="static/Images/Test.png" alt="">
                    <img id="table-2-img" src="static/Images/TestWhite.png" alt="">
                    <img id="table-3-img" src="static/Images/Test.png" alt="">
               
                  </div>              
                </div>
             </div>
            </div>

            <div class="section-2">
              <div class="section-cube-1">
                <h1>Starved</h1>
                <div class="table-2-container"> 
                  <table id="starved-tb">
                    <thead>
                      <tr>
                        <th>Week Day</th>
                        <th>Starved Time(min)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekdays, Total in weekday_starved  %}
                      <tr>
                        <td>{{ weekdays }}</td>
                        <td>{{ Total }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="stable-3-img" src="static/Images/starved.png" alt="">
                  </div>              
                </div>
              </div>
            </div>

            <div class="section-2">
              <div class="section-cube-1">
                <h1>Blocked</h1>
                <div class="table-2-container"> 
                  <table id=".blocked-tb">
                    <thead>
                      <tr>
                        <th>Weekday</th>
                        <th>Blocked Time(min)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for weekdayd, Total in weekday_blocked  %}
                      <tr>
                        <td>{{ weekdayd }}</td>
                        <td>{{ Total }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div class="img-vertical">
                    <img id="btable-3-img" src="static/Images/Blocked.png" alt="">
                    
                  </div>              
                </div>
             </div>
            </div>
            
          </div> 

      </main>  
{%endblock%}   

</html>

website/templates/base.html
<!DOCTYPE html>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.3/datatables.min.js" defer></script>

<script src="{{ url_for('static', filename='profile.js') }}" defer></script>
<script src="{{ url_for('static', filename='base.js') }}" defer></script>
<script src="{{ url_for('static', filename='comments.js') }}" defer></script>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %}</title>  
     <link rel="stylesheet" href="{{ url_for('static', filename= 'style.css')}}">
     <link rel="stylesheet" href="{{ url_for('static', filename= 'navstyle.css')}}">
     <link rel="stylesheet" href="{{ url_for('static', filename= 'comments.css')}}">
</head>

<body>
  <!--Comments Modal slide down-->
  <div class="modal" id="comment-modal" hidden>
    <div class="modal-content">
      <h2 id="modal-header">Comment</h2>
      <form id="comment-form" action="{{ url_for('views.l_474') }}" method="POST">
        
        <!-- Existing form fields -->
        <label for="line-number">Line Number:</label>
        <input type="text" name="lineNumber" id="lineNumber" readonly value="{{ lineNumb }}">
        <label for="Day of Week">Day of Week:</label>
        <input type="text" name="dayOfWeek" id="dayOfWeek" readonly value="{{ dayOfWeek }}">
        <label for="comment">Hour:</label>
        <input type="text" name="subject" id="subject" readonly value="{{ subject }}">
        <label for="comment">Comment:</label>
        <input type="text" name="comment" id="comment" required>
  
        <!-- Expander with radio buttons -->
        <div class="expander">
          <button class="expander-button" type="button">Downtime Type<span class="triangle-symbol" style="float:right;">&#9654;</span></button>

          <div class="expander-content" style="display:none;">
              <h2>Select Downtime Type:</h2>
            <div class = 'radio-wrapper'>
              <label>
                <input type="radio" name="downtimeType" value="Maintenance" checked>
                Maintenance
              </label>
              <label>
                <input type="radio" name="downtimeType" value="Changeover">
                Changeover
              </label>
              <label>
                <input type="radio" name="downtimeType" value="Blocked">
                Blocked
              </label>
              <label>
                <input type="radio" name="downtimeType" value="Starved">
                Starved
              </label>

            </div>
          </div>
        </div>
  
        <!-- Submit button and close button -->
        <button type="submit" id="submit-comment">Save</button>
        <span class="close">&times;</span>
      </form>
    </div>
  </div>



  <div class="page-layout">
    <header>
      <div class="flex-container">
        <a href="/"><span><h1><img class="logo" src="https://th.bing.com/th?id=OIP.AgxpJbcZvFTRYHqJDBtjuQHaBh&w=349&h=71&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2" alt=""></span></h1></a>
        <div class="user-login-container">
          {% if user.is_authenticated %}
          <a href="/logout"><button class="login-logout">Log-out</button></a>          
          {% else %}
          <a href="/login"><button class="login-logout">Login</button></a>
          {% endif %}
        </div> 
      </div>

      <div class="searchbox-container">
        <input type="text" id="search-input" placeholder="Filter Data..">
        <button class="search-button">
          <img class="search-icon" src="static/Images/search.png" alt="">
        </button>
        <button id="clear-search">Clear</button>
      </div>

      <!--Script of Highlighting cell values below-->
      <script>
        //Heatmap/Cell highlight
        $(document).ready(function() {
          // Initialize DataTable for data-table
          
          var data_table = $('#data-table').DataTable({
            "ordering": false,
            "searching": true,
            "dom": 'lrtip',
            "paging": false,
            "info": false,
            "searchDelay": 0,
            "createdRow": function(row, data, dataIndex) {
              // Get the cells of the current row
              var cells = $('td', row);
              // Loop through the cells and add the highlight class if the cell value meets the condition
              cells.each(function(index) {
                if (index !== cells.length - 1) { // Exclude last cell
                  var cellValue = parseInt($(this).text());
                  if (cellValue > 0 && cellValue <100) {
                    $(this).addClass('red');
                  } else if (cellValue > 100 && cellValue < 200) {
                    $(this).addClass('highlight');
                  } else if (cellValue >= 200) {
                    $(this).addClass('green');
                  }
                } else { // Highlight last cell if the value is greater than 2500
                  var cellValue = parseInt($(this).text());
                  if (cellValue > 2500) {
                    $(this).addClass('green');
                  }
                }
              });
            }
          });
          
          // Initialize DataTable for weektotals-tb
          var week_totals_table = $('#weektotals-tb').DataTable({
            "ordering": false,
            "searching": true,
            "dom": 'lrtip',
            "paging": false,
            "info": false,
            "createdRow": function(row, data, dataIndex) {
              // Get the cells of the current row
              var cells = $('td', row);
              // Highlight last cell if the value is greater than 5000
              var lastCell = cells.last();
              var cellValue = parseInt(lastCell.text());
              if (cellValue > 5000) {
                lastCell.addClass('green');
              }
            }
          });
          
          $('table').each(function() {
            if (!$.fn.DataTable.isDataTable(this)) {
              $(this).DataTable({
                "ordering": false,
                "searching": true,
                "dom": 'lrtip',
                "paging": false,
                "info": false
              });
            }
          });
          
          // Get all DataTables on the page
          var tables = $.fn.dataTable.tables();
          
          // Search function for all tables
          function searchAllTables(searchTerm) {
            $.each(tables, function() {
              $(this).DataTable().search(searchTerm).draw();
            });
          }
          
          // Add search and clear search functionality to all tables
          $('.search-button').click(function() {
            var searchTerm = $('#search-input').val();
            searchAllTables(searchTerm);
          });
          
          $('#clear-search').click(function() {
            $('#search-input').val('');
            searchAllTables('');
            $(this).hide();
          });
          
          $('#search-input').keyup(function() {
            searchAllTables($(this).val());
          });
          
          // Show or hide clear search button based on search input
          $.each(tables, function() {
            var currentTable = $(this).DataTable();
            currentTable.on('search.dt', function() {
              if (currentTable.search()) {
                $('#clear-search').show();
              } else {
                $('#clear-search').hide();
              }
            });
          });
        });
      </script>    
        <div class="navbuttons">
          <a href="https://www.plexonline.com/ece3221b-ff0c-4f65-8bb9-9954071c0a88/Modules/SystemAdministration/MenuSystem/menu.aspx?Node=3114307" target="_blank"><button>Plex Login</button></a>
      
        </div>
      
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{category}}">
          <h2>{{message}}</h2>
        </div>
        <script>
          function hideMessage(element) {
            element.style.display = 'none';
          }
          setTimeout(function() {
            document.querySelector('.alert').remove();
          }, 2000); // hide message after 2 seconds
        </script>
      {% endfor %}
    {% endif %}
  {% endwith %}
    
 

      {% block header %}
      {% endblock %}
      <div class="lineNumber">
        <div class="clock-container">
          {% if user.is_authenticated %}
            {% if not request.path.startswith('/profile')  and not request.path.startswith('/admin')  %}
              <a href="/profile"><span onclick="openNav()" class="user-greeting"><h1>Welcome {{user.first_name}}</h1></span></a>
            {% else %}
            <span onclick="openNav()" class="user-greeting"><h1>Welcome {{user.first_name}}</h1></span>
            {% endif %}
          {% endif %}  
          {% if request.path != '/' %}
          <div class="dropdown">
            <button class="dropbtn">Line Navigation</button>
            <div class="dropdown-content">
              <a class="dropdown-link" href="/471">471</a>
              <a class="dropdown-link" href="/474">474</a>
              <a class="dropdown-link" href="/424">424</a>
              <a class="dropdown-link" href="/429">429</a>
              <a class="dropdown-link" href="/456">456</a>
              <a class="dropdown-link" href="/457">457</a>
              <a class="dropdown-link" href="/458">458</a>
              <a class="dropdown-link" href="/461">461</a>
            </div>
          </div>
          {% endif %}     
          <h1 id="datetime"></h1>
        </div>  
      </div>
      <script src="{{ url_for('static', filename='clock.js') }}" defer></script>
      <div id="main">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <footer>
      <p>All rights reserved @2023</p>
    </footer>
</body>

</html>